# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-03 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSmell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CodeSmellInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_part_of_agglomeration', models.BooleanField()),
                ('affected_element', models.CharField(max_length=1000)),
                ('reason', models.TextField()),
                ('is_smell', models.BooleanField()),
                ('smell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summaries.CodeSmell')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_fqn', models.CharField(max_length=1000)),
                ('observations', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='codesmellinstance',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summaries.Summary'),
        ),
    ]
