# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-03 21:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSmell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CodeSmellInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_part_of_agglomeration', models.BooleanField()),
                ('affected_element', models.CharField(max_length=1000)),
                ('reason', models.TextField()),
                ('smell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summaries.CodeSmell')),
            ],
        ),
        migrations.CreateModel(
            name='DesignPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DesignPatternInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elements_involved', models.TextField(default='')),
                ('design_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summaries.DesignPattern')),
            ],
        ),
        migrations.CreateModel(
            name='DesignPrinciple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DesignPrincipleInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_principle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summaries.DesignPrinciple')),
            ],
        ),
        migrations.CreateModel(
            name='NonFunctionalAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NonFunctionalAttributeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non_functional_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summaries.NonFunctionalAttribute')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_fqn', models.CharField(max_length=1000)),
                ('agglomeration', models.TextField(blank=True, null=True)),
                ('similar_summaries', models.ManyToManyField(blank=True, to='summaries.Summary')),
            ],
            options={
                'verbose_name': 'Summary',
                'verbose_name_plural': 'Summaries',
            },
        ),
        migrations.CreateModel(
            name='SummaryAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations', models.TextField(default='')),
                ('agglomeration_rating', models.CharField(blank=True, choices=[('0', 'Irrelevante'), ('1', 'Relevante'), ('2', 'Muito Relevante')], default='0', max_length=1, null=True)),
                ('design_patterns_rating', models.CharField(blank=True, choices=[('0', 'Irrelevante'), ('1', 'Relevante'), ('2', 'Muito Relevante')], default='0', max_length=1, null=True)),
                ('smells_rating', models.CharField(blank=True, choices=[('0', 'Irrelevante'), ('1', 'Relevante'), ('2', 'Muito Relevante')], default='0', max_length=1, null=True)),
                ('design_principles_rating', models.CharField(blank=True, choices=[('0', 'Irrelevante'), ('1', 'Relevante'), ('2', 'Muito Relevante')], default='0', max_length=1, null=True)),
                ('examples_rating', models.CharField(blank=True, choices=[('0', 'Irrelevante'), ('1', 'Relevante'), ('2', 'Muito Relevante')], default='0', max_length=1, null=True)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summaries.Summary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='summary',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summaries.System'),
        ),
        migrations.AddField(
            model_name='nonfunctionalattributeinstance',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='summaries.Summary'),
        ),
        migrations.AddField(
            model_name='designprincipleinstance',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='summaries.Summary'),
        ),
        migrations.AddField(
            model_name='designpatterninstance',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='summaries.Summary'),
        ),
        migrations.AddField(
            model_name='codesmellinstance',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='summaries.Summary'),
        ),
    ]
