# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-03 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'verbose_name': 'Summary', 'verbose_name_plural': 'Summaries'},
        ),
        migrations.RemoveField(
            model_name='summary',
            name='observations',
        ),
        migrations.AlterField(
            model_name='codesmellinstance',
            name='is_smell',
            field=models.BooleanField(default=False),
        ),
    ]
