# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-04 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0002_usersubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryAnswerCodeSmell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_smell', models.BooleanField()),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summaries.CodeSmellInstance')),
                ('summary_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summaries.SummaryAnswer')),
            ],
        ),
    ]
