# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-03 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0003_auto_20170403_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonFunctionalAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NonFunctionalAttributeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non_functional_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summaries.NonFunctionalAttribute')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summaries.Summary')),
            ],
        ),
    ]
