# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-03 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0004_nonfunctionalattribute_nonfunctionalattributeinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='summaries.Summary')),
            ],
        ),
        migrations.AlterField(
            model_name='codesmellinstance',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='summaries.Summary'),
        ),
        migrations.AlterField(
            model_name='designprincipleinstance',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='summaries.Summary'),
        ),
        migrations.AlterField(
            model_name='nonfunctionalattributeinstance',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='summaries.Summary'),
        ),
    ]
