# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-03 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0005_auto_20170403_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='similarsummary',
            name='summary',
        ),
        migrations.AddField(
            model_name='summary',
            name='similar_summaries',
            field=models.ManyToManyField(to='summaries.Summary'),
        ),
        migrations.DeleteModel(
            name='SimilarSummary',
        ),
    ]
