# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-07 19:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0005_auto_20170407_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designpatterninstance',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='designprincipleinstance',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='nonfunctionalattributeinstance',
            name='reason',
        ),
        migrations.AlterField(
            model_name='codesmellinstance',
            name='reason',
            field=models.TextField(default=datetime.datetime(2017, 4, 7, 19, 9, 50, 436110, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
