# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-03 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0006_auto_20170403_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DesignPatternInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summaries.DesignPattern')),
                ('summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='summaries.Summary')),
            ],
        ),
    ]
