# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-07 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0006_auto_20170407_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryanswer',
            name='non_functional_ratings',
            field=models.CharField(blank=True, choices=[('0', 'Irrelevante'), ('1', 'Relevante'), ('2', 'Muito Relevante')], default='0', max_length=1, null=True),
        ),
    ]
