# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-03 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0007_designpattern_designpatterninstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='designpatterninstance',
            name='elements_involved',
            field=models.TextField(default=''),
        ),
    ]
