# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-03 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0008_designpatterninstance_elements_involved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agglomeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summaries.Summary')),
            ],
        ),
        migrations.CreateModel(
            name='AgglomerationElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fqn', models.CharField(max_length=250)),
                ('agglomeration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summaries.Agglomeration')),
            ],
        ),
        migrations.CreateModel(
            name='ElementRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('A', 'Association'), ('DA', 'Directed Association'), ('AG', 'Aggregation'), ('C', 'Composition'), ('I', 'Inheritance'), ('R', 'Realization')], default='A', max_length=2)),
                ('element_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_from', to='summaries.AgglomerationElement')),
                ('element_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_to', to='summaries.AgglomerationElement')),
            ],
        ),
    ]
