# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-03 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0009_agglomeration_agglomerationelement_elementrelationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agglomeration',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='agglomerationelement',
            name='agglomeration',
        ),
        migrations.AddField(
            model_name='agglomeration',
            name='elements',
            field=models.ManyToManyField(to='summaries.AgglomerationElement'),
        ),
        migrations.AddField(
            model_name='agglomeration',
            name='relationships',
            field=models.ManyToManyField(to='summaries.ElementRelationship'),
        ),
        migrations.AddField(
            model_name='summary',
            name='agglomeration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='summaries.Agglomeration'),
        ),
    ]
