# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-10 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0009_auto_20170410_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('is_complete', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='experiment_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='system_name',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='type',
        ),
        migrations.DeleteModel(
            name='SummaryType',
        ),
        migrations.AddField(
            model_name='experiment',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='summaries.System'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='summaries.ExperimentType'),
        ),
    ]
