# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-10 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0010_auto_20170410_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaryanswer',
            name='agglomeration_rating',
            field=models.CharField(blank=True, choices=[('0', 'Irrelevante'), ('1', 'Pouco Relevante'), ('2', 'Bastante Relevante'), ('3', 'Muito Relevante')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='summaryanswer',
            name='design_patterns_rating',
            field=models.CharField(blank=True, choices=[('0', 'Irrelevante'), ('1', 'Pouco Relevante'), ('2', 'Bastante Relevante'), ('3', 'Muito Relevante')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='summaryanswer',
            name='design_principles_rating',
            field=models.CharField(blank=True, choices=[('0', 'Irrelevante'), ('1', 'Pouco Relevante'), ('2', 'Bastante Relevante'), ('3', 'Muito Relevante')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='summaryanswer',
            name='examples_rating',
            field=models.CharField(blank=True, choices=[('0', 'Irrelevante'), ('1', 'Pouco Relevante'), ('2', 'Bastante Relevante'), ('3', 'Muito Relevante')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='summaryanswer',
            name='non_functional_ratings',
            field=models.CharField(blank=True, choices=[('0', 'Irrelevante'), ('1', 'Pouco Relevante'), ('2', 'Bastante Relevante'), ('3', 'Muito Relevante')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='summaryanswer',
            name='smells_rating',
            field=models.CharField(blank=True, choices=[('0', 'Irrelevante'), ('1', 'Pouco Relevante'), ('2', 'Bastante Relevante'), ('3', 'Muito Relevante')], default=None, max_length=1, null=True),
        ),
    ]
