# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-10 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0011_auto_20170410_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='designpatterninstance',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designprincipleinstance',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonfunctionalattributeinstance',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
