# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-11 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0012_auto_20170410_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
