# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-22 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0014_codesmellopinion_is_smell'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimenttype',
            name='should_get_feedback',
            field=models.BooleanField(default=True),
        ),
    ]
