# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-22 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0015_experimenttype_should_get_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimenttype',
            name='should_get_feedback',
        ),
        migrations.AddField(
            model_name='experiment',
            name='should_get_feedback',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='should_present_validation_field',
            field=models.BooleanField(default=True),
        ),
    ]
