# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-05 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcharacterizationsurvey',
            name='experience',
            field=models.IntegerField(verbose_name='Experi\xeancia em desenvolvimento de software (em anos) na ind\xfastria'),
        ),
        migrations.AlterField(
            model_name='subjectcharacterizationsurvey',
            name='experience_java',
            field=models.IntegerField(verbose_name='Experi\xeancia com linguagem de programa\xe7\xe3o Java (em anos) na ind\xfastria'),
        ),
        migrations.AlterField(
            model_name='subjectcharacterizationsurvey',
            name='projects_java',
            field=models.IntegerField(verbose_name='Quantos projetos em Java voc\xea trabalhou na ind\xfastria?'),
        ),
    ]
